### ISSUE TITLE
Exception is thrown when sharedStrings.xml contains 'phoneticProperties'

### ISSUE THREAD

**Issue by StanBertrand** [pjfanning/poi-shared-strings#62]
Hello !

I try to read an Excel containing phonetic hints. 
So, I have 'phonetic properties' (`phoneticPr`) and 'phonetic run' (`rPh`) XML tag inside the file `sharedStrings.xml`.

When, I read this file I have an exception : 
```
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,113]
Message: found: CHARACTERS, expected START_ELEMENT or END_ELEMENT
	at java.xml@15.0.6/com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.nextTag(XMLStreamReaderImpl.java:1361)
	at java.xml@15.0.6/com.sun.xml.internal.stream.XMLEventReaderImpl.nextTag(XMLEventReaderImpl.java:242)
	at app//com.github.pjfanning.poi.xssf.streaming.TextParser.skipElement(TextParser.java:121)
	at app//com.github.pjfanning.poi.xssf.streaming.TextParser.skipElement(TextParser.java:122)
	at app//com.github.pjfanning.poi.xssf.streaming.TextParser.parseCT_Rst(TextParser.java:43)
	at app//com.github.pjfanning.poi.xssf.streaming.SharedStringsTableBase.readFrom(SharedStringsTableBase.java:136)
```

This exception occured when `SharedStringsTableBase.fullFormat = false`

### Test to reproduce :
```
public void testReadXML_with_phonetic() throws Exception {
        try (InputStream is = TestTempFileSharedStringsTable.class.getClassLoader().getResourceAsStream("sharedStrings_with_phonetics.xml");
             TempFileSharedStringsTable sst = new TempFileSharedStringsTable(false, true)) {
            sst.readFrom(is);
        }
    } 
```
with `sharedStrings_with_phonetics.xml` : 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><si><t>沖縄</t><rPh sb="0" eb="2"><t>オキナワ</t></rPh><phoneticPr fontId="2"/></si></sst>
```

I think we can replace in `TextParser.skipElement` : `xmlEventReader.nextTag()` in `xmlEventReader.nextEvent()`. 
What do you think ?
I already do the PR with tests in local if you want !

**Comment by pjfanning** [comment]
sure - try a PR - advantage of PRs is that there is a CI build that runs tests

**Comment by StanBertrand** [comment]
https://github.com/pjfanning/poi-shared-strings/pull/63

**Comment by pjfanning** [comment]
I added https://github.com/pjfanning/poi-shared-strings/commit/172b82945b461528138ca176f0f1cf82c1e38418 - seems best to use nextEvent() everywhere.

**Comment by StanBertrand** [comment]
Cool ! Thanks a lot ! Can we do a release ?

**Comment by pjfanning** [comment]
v2.5.6 is released
